### PR TITLE
Support L3 level primitives

### PR DESCRIPTION
**Pull request by kballeda**
This PR contains following primitives from level - 3.

Symmetric: symm, syrk, syr2k
Triangular: trmm, trsm
Hermitian: hemm, herk, her2k

### CODE REVIEW

**Comment by kballeda** [comment]
image
CI run results of this PR.

**Comment by kballeda** [comment]
image

**Comment by kballeda** [comment]
image

**Comment by kballeda** [comment]
Hi @pengtu / @Sarbojit2019  - Please review this PR.
Merge conflicts that you see here are coming from L2 changes in dev branch. This PR is mainly for L3 primitives.

**Review by pengtu — APPROVED** [review]
Looks very good!  Thank you.

**Comment by kballeda** [comment]
> Looks very good! Thank you.

Thanks for the review.

**Pull request closed without merging**
