### PR TITLE
Oneapi 2024

### PR DESCRIPTION
**Pull request by amontoison**
@kballeda 
`iamin` and `iamax` requires an additional argument with oneAPI 2024 to specify the index base.
We need to specify it explicitly in Julia (1-based indexing).
I also updated `generate_interfaces.jl`.

Related PR: https://github.com/JuliaGPU/oneAPI.jl/pull/386.

### CODE REVIEW

**Comment by amontoison** [comment]
We also need to regenerate the Julia wrappers in the folder `res`.
Can you do it?

**Comment by kballeda** [comment]
> @kballeda `iamin` and `iamax` requires an additional argument with oneAPI 2024 to specify the index base. We need to specify it explicitly in Julia (1-based indexing). I also updated `generate_interfaces.jl`.
> 
> Related PR: [JuliaGPU#386](https://github.com/JuliaGPU/oneAPI.jl/pull/386).

@amontoison  Can you please share more insights into this topic, why do we need this change for only these two primitives.

**Comment by amontoison** [comment]
Because only these BLAS routines return an integer value that depends on the indexing.
`iamin` and `iamax` return the position of the minimum / maximum coefficient in an array.

Only the C++ header of these two routines were updated and have an additional a parameter.
But it's an optional argument, it's why it was working without updating the Julia wrappers.

I suppose that before oneAPI 2024, only 0-based indexing was supported in these routines.

**Comment by amontoison** [comment]
I checked how we interfaced `iamin` and `iamax` and we are doing the +1 by hand at the end of the Julia function:
https://github.com/kballeda/oneAPI.jl/blob/master/lib/mkl/wrappers.jl#L864

**Comment by kballeda** [comment]
> I checked how we interfaced `iamin` and `iamax` and we are doing the +1 by hand at the end of the Julia function: https://github.com/kballeda/oneAPI.jl/blob/master/lib/mkl/wrappers.jl#L864

Excellent Catch !!

**Comment by amontoison** [comment]
If we update the Julia wrappers, we can just replace
```julia
$fname(sycl_queue(queue), n, x, stride(x, 1), result)
```
by
```julia
$fname(sycl_queue(queue), n, x, stride(x, 1), result, 'O')
```
and remove the +1 at the end.

Finally, it's not so important 😅

At least the script `julia_interfaces.jl` is working with the new headers and that's what we want for the maintenance.

**Pull request closed without merging**
