### PR TITLE
Level - 2 gbmv support

### PR DESCRIPTION
**Pull request by kballeda**

### CODE REVIEW

**Comment by kballeda** [comment]
l2_gbmv_pass

**Comment by pengtu** [comment]
Looks good!

**Comment by kballeda** [comment]
image

CR run results - Pass

**Comment by kballeda** [comment]
image
Latest run all level-2 primitives together except tbsv

**Comment by kballeda** [comment]
@pengtu  / @Sarbojit2019  : Please review this PR.

**Comment by pengtu** [comment]
Please also update linalg.jl to use the new trmv, trsv functions. Search in cublas/linalg.jl for trmv, trsv, there are several hits.  Here is a case: 

https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cublas/linalg.jl#L213

Or you can merge this first and add the linalg.jl changes in a separate change set.

**Comment by kballeda** [comment]
> Please also update linalg.jl to use the new trmv, trsv functions. Search in cublas/linalg.jl for trmv, trsv, there are several hits. Here is a case:
> 
> https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cublas/linalg.jl#L213

@pengtu  we have updated the linalg.jl as well: https://github.com/kballeda/oneAPI.jl/blob/340cfdedf5a5f22e76a0fd5eb9cf169208792afa/lib/mkl/linalg.jl#L115

**Comment by pengtu** [comment]
> > Please also update linalg.jl to use the new trmv, trsv functions. Search in cublas/linalg.jl for trmv, trsv, there are several hits. Here is a case:
> > https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cublas/linalg.jl#L213
> 
> @pengtu we have updated the linalg.jl as well:
> 
> https://github.com/kballeda/oneAPI.jl/blob/340cfdedf5a5f22e76a0fd5eb9cf169208792afa/lib/mkl/linalg.jl#L115

My bad.  I clicked a wrong link.  Thanks!

**Review by Sarbojit2019 — APPROVED** [review]

**Pull request merged**
